package com.lou.mybatisgen.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Id
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Name
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Age
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Id
     *
     * @return the value of User.Id
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Id
     *
     * @param id the value for User.Id
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Name
     *
     * @return the value of User.Name
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Name
     *
     * @param name the value for User.Name
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Age
     *
     * @return the value of User.Age
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Age
     *
     * @param age the value for User.Age
     *
     * @mbg.generated Mon Jul 22 09:29:25 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}